# Generated by Django 2.0.4 on 2018-12-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creation_date',
            new_name='timestamp',
        ),
    ]
