# Generated by Django 2.0.4 on 2018-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_firstaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaid',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
