# Generated by Django 2.0.4 on 2018-09-02 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180902_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item name')),
                ('price_per_piece', models.IntegerField()),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Item picture')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item name')),
                ('price_per_piece', models.IntegerField()),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Item picture')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item name')),
                ('price_per_piece', models.IntegerField()),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Item picture')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FirstAid',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
