# Generated by Django 2.0.4 on 2018-09-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20180902_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perlength',
            old_name='price_per_piece',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='perpiece',
            old_name='price_per_piece',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='perweight',
            old_name='price_per_piece',
            new_name='price',
        ),
    ]
