# Generated by Django 2.0.4 on 2018-09-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20180904_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='perlength',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perlength',
            name='required_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perpiece',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perpiece',
            name='required_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perweight',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perweight',
            name='required_stock',
            field=models.IntegerField(default=0),
        ),
    ]
