# Generated by Django 2.0.4 on 2018-09-05 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20180905_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='perlength',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perlength',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perlength',
            name='need_to_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perlength',
            name='not_in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perpiece',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perpiece',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perpiece',
            name='need_to_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perpiece',
            name='not_in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perweight',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perweight',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perweight',
            name='need_to_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perweight',
            name='not_in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perlength',
            name='required_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='perpiece',
            name='required_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='perweight',
            name='required_stock',
            field=models.IntegerField(default=1),
        ),
    ]
