# Generated by Django 2.0.4 on 2018-09-06 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0007_auto_20180906_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='perlength',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perpiece',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perweight',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perlength',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='perpiece',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='perweight',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Short description'),
        ),
    ]
