# Generated by Django 2.0.4 on 2018-09-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20180906_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perlength',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='perpiece',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='perweight',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Short description'),
        ),
    ]
