# Generated by Django 2.0.4 on 2018-09-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20180907_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perlength',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pics/%Y-%m-%d/', verbose_name='Item picture'),
        ),
        migrations.AlterField(
            model_name='perpiece',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pics/%Y-%m-%d/', verbose_name='Item picture'),
        ),
        migrations.AlterField(
            model_name='perweight',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pics/%Y-%m-%d/', verbose_name='Item picture'),
        ),
    ]
