# Generated by Django 2.0.4 on 2018-12-03 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0010_auto_20180907_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerPiece',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='perlength',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='perweight',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='PerLength',
        ),
        migrations.DeleteModel(
            name='PerWeight',
        ),
    ]
