# Generated by Django 2.0.4 on 2018-09-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='Male', max_length=6),
        ),
    ]
