# Generated by Django 2.0.4 on 2018-09-08 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Provider name')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='Male', max_length=6)),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='provider_pics/%Y-%m-%d/', verbose_name='Provider photo')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Short description')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('made_vip_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
