# Generated by Django 2.0.4 on 2018-09-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='sex',
        ),
        migrations.AddField(
            model_name='provider',
            name='is_reputed',
            field=models.BooleanField(default=False),
        ),
    ]
